#!/bin/bash
# This script helps run rstudio-server with CondaTainer env.

PORT=8787
AUTH="none"

OVERLAYS_ARG=""
OVERLAYS=""
OVERLAY="env.img"
FAKE_ROOT_ARG=""
CWD=$(readlink -f .)

CONDATAINER_CONFIG_DIR="$HOME/.config/condatainer"
mkdir -p $CONDATAINER_CONFIG_DIR

RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_help() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -p <port>       Port for rstudio-server (default: $PORT)"
    echo "  -e <overlay>    Environment overlay image file (default: $OVERLAY)"
    echo "  -o <overlay>    Additional overlay files (can have multiple -o options)"
    echo "  -f              Use fakeroot mode (will be root inside the container)"
    echo "  -y              Accept all warnings and proceed"
    echo "  -h              Show this help message"
}

while getopts "p:e:o:fyh" opt; do
    case ${opt} in
        p ) PORT=$OPTARG ;;
        e ) OVERLAY=$OPTARG ;;
        o ) OVERLAYS_ARG+=" -o $OPTARG"; OVERLAYS+=" $OPTARG" ;;
        f ) FAKE_ROOT_ARG="--fakeroot"; echo "Using fakeroot mode" ;;
        y ) AUTO_YES=true ;;
        h ) print_help; exit 0 ;;
        \? ) print_help; exit 1 ;;
    esac
done

#region Sanity Checks
if lsof -i :$PORT &> /dev/null; then
    echo -e "${RED}[ERROR]${NC} Port ${BLUE}$PORT${NC} is already in use."
    echo -e "Please choose a different port using the ${YELLOW}-p${NC} option."
    exit 1
fi

ID=$(id -u)
if [ $ID -lt 1000 ]; then
    echo -e "${RED}[ERROR]${NC} Cannot run rstudio-server as UID less than 1000."
    echo -e "Please create a user with UID higher than 1000 to run it."
    exit 1
fi
if [ $ID -eq 1000 ]; then
    echo -e "${RED}[ERROR]${NC} Cannot run rstudio-server as UID 1000. (Used by default user in Ubuntu-based containers)"
    echo -e "Please create a user with UID other than 1000 to run it."
    exit 1
fi

if ! command -v condatainer &> /dev/null; then
    echo -e "${RED}[ERROR]${NC} CondaTainer is not installed or not in PATH."
    echo -e "Please go to https://github.com/Justype/condatainer to install CondaTainer."
    exit 1
fi

missing=""
for pkg in rstudio-server texlive build-essential $OVERLAYS; do
    if ! condatainer ls $pkg | grep -q $pkg; then
        missing+=" $pkg"
    fi
done
if [ -n "$missing" ]; then
    echo -e "${RED}[ERROR]${NC} The following required overlays are missing:${missing}."
    echo -e "Please run 'condatainer install$missing'"
    if [ -z "$AUTO_YES" ]; then
        echo -e "Do you want to install them now? [Y/n]"
        read answer
    else
        answer="Y"
    fi
    if [[ "$answer" == "Y" || "$answer" == "y" || "$answer" == "" ]]; then
        condatainer install $missing
        if [ $? -ne 0 ]; then
            echo -e "${RED}[ERROR]${NC} Failed to install required overlays."
            exit 1
        fi
    else
        exit 1
    fi
fi

if [ ! -f "$OVERLAY" ]; then
    echo -e "${RED}[ERROR]${NC} Overlay ${BLUE}$OVERLAY${NC} not found."
    exit 1
else
    PID_LIST=$(lsof $OVERLAY 2>/dev/null | awk 'NR>1 {print $2}' | sort -u)
    if [ -n "$PID_LIST" ]; then
        echo -e "${YELLOW}[WARNING]${NC} Overlay ${BLUE}$OVERLAY${NC} is currently in use by the following processes:"
        echo "$PID_LIST"
        if [ "$AUTO_YES" = true ]; then
            response="y"
        else
            echo -e "Do you want to kill these processes and continue? [y/N]"
            read -r response
        fi

        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            echo -e "Aborting as per user request."
            exit 1
        else
            for pid in $PID_LIST; do
                kill -9 $pid
            done
            echo -e "${BLUE}[INFO]${NC} Killed processes using the overlay."
        fi
    fi
    echo -e "Using overlay: ${BLUE}$OVERLAY${NC}"
    OVERLAY_ARG="-o $OVERLAY"
    ABS_OVERLAY_PATH=$(readlink -f $OVERLAY)
    CWD=$(dirname $ABS_OVERLAY_PATH) # Set CWD to overlay directory
    if ! debugfs -R "stat upper/ext3/env/bin/R" $OVERLAY 2>&1 | grep -q 'Inode'; then
        echo -e "${RED}[ERROR]${NC} Overlay ${BLUE}$OVERLAY${NC} does not contain R installation."
        echo -e "Please go into the overlay shell and run 'mm-install r-base' to install R."
        exit 1
    fi
    # Check and repair overlay image
    echo -e "Checking overlay image integrity..."
    e2fsck -p $OVERLAY > /dev/null 2>&1
    e2fsck -p $OVERLAY > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo -e "${RED}[ERROR]${NC} Overlay ${BLUE}$OVERLAY${NC} is corrupted and could not be repaired."
        echo -e "Please run ${YELLOW}e2fsck $OVERLAY${NC} manually to attempt repair."
        exit 1
    fi
    R_BIN_PATH="/ext3/env/bin/R"
    R_LIB_PATH="/ext3/env/lib"
fi

if [ -z "$SCRATCH" ]; then
    echo -e "${YELLOW}[WARNING]${NC} SCRATCH environment variable is not set. Falling back to HOME directory."
    SCRATCH="$HOME"
fi
#endregion

CWD_FOLDER_NAME=$(basename $CWD)
RPROJECT_FILE="$CWD/$CWD_FOLDER_NAME.Rproj"
if ! [ -f "$RPROJECT_FILE" ]; then
    echo -e "${BLUE}[INFO]${NC} Creating RStudio project file at ${BLUE}$RPROJECT_FILE${NC}."
    cat <<EOT > $RPROJECT_FILE
Version: 1.0

RestoreWorkspace: Default
SaveWorkspace: Default
AlwaysSaveHistory: Default

EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 2
Encoding: UTF-8

RnwWeave: Sweave
LaTeX: pdfLaTeX
EOT
fi
cat <<EOT > $CONDATAINER_CONFIG_DIR/rsession.sh
#!/bin/bash

USER=`whoami`
source /etc/profile

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi
source $HOME/.bashrc

export MAMBA_ROOT_PREFIX=/ext3/env
export CONDA_PREFIX=/ext3/env
export CONDA_DEFAULT_ENV=env
export CNT_CONDA_PREFIX=/ext3/env
export RETICULATE_PYTHON=/ext3/env/bin/python

/usr/lib/rstudio-server/bin/rsession "\$@"
EOT
chmod +x $CONDATAINER_CONFIG_DIR/rsession.sh
cat <<EOT > $CONDATAINER_CONFIG_DIR/rsession.conf
copilot-enabled=1
session-default-working-dir=$CWD
EOT
cat <<EOT > $CONDATAINER_CONFIG_DIR/database.conf
provider=sqlite
directory=$SCRATCH/.local/lib/rstudio-server
EOT

sleep 1

echo -e "rstudio-server at ${BLUE}http://localhost:${PORT}${NC}"
echo -e "You can run the following command in R to open the project directly:"
echo -e "  ${YELLOW}rstudioapi::openProject(\"$CWD\")${NC}"

condatainer exec \
    -o rstudio-server \
    -o texlive \
    -o build-essential \
    $OVERLAYS_ARG \
    $OVERLAY_ARG --writable-img \
    $FAKE_ROOT_ARG \
    /usr/lib/rstudio-server/bin/rserver \
        --server-user $USER \
        --server-daemonize=0 \
        --server-data-dir=$SCRATCH/.local/run/rstudio-server \
        --www-address=127.0.0.1 \
        --www-port=$PORT \
        --rsession-which-r=$R_BIN_PATH \
        --rsession-path=$CONDATAINER_CONFIG_DIR/rsession.sh \
        --rsession-ld-library-path=$R_LIB_PATH \
        --database-config-file=$CONDATAINER_CONFIG_DIR/database.conf \
        --rsession-config-file=$CONDATAINER_CONFIG_DIR/rsession.conf \
        --auth-none=1
