# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04

python:
  version: 3.10
  install:
    - method: pip
      path: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

# Valid formats are: htmlzip, pdf, epub
formats: ['htmlzip']
