#!/usr/bin/bash
#DEP:grch38/genome/gencode
#DEP:grch38/transcript-gencode/33
#DEP:salmon/1.10.2
#WHATIS:Salmon grch38 GENCODE 33 index for transcript quantification
#URL:https://combine-lab.github.io/salmon/
#ENV:SALMON_INDEX_DIR=$app_root
#ENVNOTE:Salmon index for grch38 GENCODE v33

#SBATCH --cpus-per-task=16
#SBATCH --mem=24G
#SBATCH --time=2:00:00
#SBATCH --job-name=salmon-index
#SBATCH --output=%x-%j.log

#########################################################
# - https://combine-lab.github.io/salmon/
# - https://salmon.readthedocs.io/en/latest/salmon.html#preparing-transcriptome-indices-mapping-based-mode
#########################################################

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    print_stderr "Appending genome to transcriptome and generating decoys..."

    cat "$TRANSCRIPT_FASTA" > gentrome.fa
    cat "$GENOME_FASTA" >> gentrome.fa

    if [ -f "${GENOME_FASTA}.fai" ]; then
        print_stderr "Using existing ${YELLOW}${GENOME_FASTA}.fai${NC} to generate decoys"
        cat "${GENOME_FASTA}.fai" | cut -f 1 > decoys.txt
    else
        print_stderr "Using fastq header lines to generate decoys"
        cat "$GENOME_FASTA" | \
            grep "^>" | \
            cut -d " " -f 1 | \
            sed 's/^>//' \
            > decoys.txt
    fi

    print_stderr "Building Salmon index for ${YELLOW}${app_name_version}${NC}"
    salmon index \
        -p $NCPUS \
        -t gentrome.fa \
        -d decoys.txt \
        -i "$target_dir" \
        --gencode
}

# Available variables:
# - NCPUS: number of cores to use (default: 4; set by condatainer)
# - app_name:         name     of the app (set by condatainer)
# - version:          version  of the app (set by condatainer)
# - app_name_version: name/version        (set by condatainer)

# - target_dir:       opt/assembly/data_type/version (set by condatainer)
# - tmp_dir:          tmp directory (set by condatainer)

# region common_functions
set -e # exit on error
RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color
NCPUS=${NCPUS:-4}   # number of cores to use when building from source

install() {
    print_stderr "Installing the target module: ${YELLOW}${app_name_version}${NC}"
    print_stderr "🎯 Target directory: $target_dir"
    # if target directory exists, exit 1
    if [ -d "$target_dir" ]; then
        print_stderr "${RED}ERROR${NC}: Target app dir exists!"
        print_stderr "Exit Installing"
        exit 1
    fi

    if [[ -z "$tmp_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: tmp_dir is not set!"
        print_stderr "Exit Installing"
        exit 1
    fi

    if [[ -z "$target_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: target_dir is not set!"
        print_stderr "Exit Installing"
        exit 1
    fi

    mkdir -p "$target_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    install_app
    print_stderr "✅ Installation completed. ${YELLOW}${app_name_version}${NC} is ready to use."
}

print_stderr() {
    printf "[`date +"%Y-%m-%d %T"`] $1\n" 1>&2
}

pigz_or_gunzip() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $NCPUS "$1"
    else
        gunzip "$1"
    fi
}

pigz_or_gunzip_pipe() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $NCPUS -c "$1"
    else
        gunzip -c "$1"
    fi
}

tar_xf_pigz() {
    if command -v pigz &> /dev/null; then
        tar --no-same-owner --use-compress-program="pigz -d -p $NCPUS" -xf "$@"
    else
        tar --no-same-owner -xzf "$@"
    fi
}
#endregion

install
