#!/usr/bin/bash
#WHATIS:<index description>
#URL:<indexer URL>

## Make sure you list all dependencies required for building the data
#DEP:bowtie2/2.5.4
#DEP:grch38/genome/ucsc_no_alt

## In env $app_root is a placeholder for the actual installation path
## Please check the MANUAL_BUILD_SCRIPT.md for env naming conventions
#ENV:BOWTIE2_PREFIX=$app_root/GRCh38_no_alt_analysis_set
#ENVNOTE:GRCh38 reference genome

# If you just download data, remove the SBATCH lines
#SBATCH --cpus-per-task=12
#SBATCH --mem=12G
#SBATCH --time=2:00:00
#SBATCH --job-name=bowtie2-build
#SBATCH --output=%x-%j.log

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    cd "$target_dir"

    BOWTIE2_PREFIX="GRCh38_no_alt_analysis_set"

    print_stderr "Indexing ${YELLOW}${app_name_version}${NC} with bowtie2-build"
    bowtie2-build --threads "$ncpu" "$GENOME_FASTA" "$BOWTIE2_PREFIX"
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK
# - app_name:         name     of the app (set by condatainer)
# - version:          version  of the app (set by condatainer)
# - app_name_version: name/version        (set by condatainer)

# - target_dir:       opt/assembly/data_type/version (set by condatainer)
# - tmp_dir:          tmp directory (set by condatainer)

# region common_functions
set -e # exit on error
RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color
ncpu=${SLURM_CPUS_PER_TASK:-4} # number of cores to use when building from source

install() {
    print_stderr "Installing the target module: ${YELLOW}${app_name_version}${NC}"
    print_stderr "🎯 Target directory: $target_dir"
    # if target directory exists, exit 1
    if [ -d "$target_dir" ]; then
        print_stderr "${RED}ERROR${NC}: Target app dir exists!"
        print_stderr "Exit Installing"
        exit 1
    fi

    if [[ -z "$tmp_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: tmp_dir is not set!"
        print_stderr "Exit Installing"
        exit 1
    fi

    if [[ -z "$target_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: target_dir is not set!"
        print_stderr "Exit Installing"
        exit 1
    fi

    mkdir -p "$target_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    install_app
    print_stderr "✅ Installation completed. ${YELLOW}${app_name_version}${NC} is ready to use."
}

print_stderr() {
    printf "[`date +"%Y-%m-%d %T"`] $1\n" 1>&2
}

pigz_or_gunzip() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $ncpu "$1"
    else
        gunzip "$1"
    fi
}

pigz_or_gunzip_pipe() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $ncpu -c "$1"
    else
        gunzip -c "$1"
    fi
}

tar_xf_pigz() {
    if command -v pigz &> /dev/null; then
        tar --no-same-owner --use-compress-program="pigz -d -p $ncpu" -xf "$@"
    else
        tar --no-same-owner -xzf "$@"
    fi
}

in_apptainer() {
    if [[ -n "$APPTAINER_NAME" || -n "$SINGULARITY_NAME" || \
          -d /.singularity.d || -d /.apptainer.d ]]; then
        return 1
    else
        return 0
    fi
}

smart_copy_or_link() {
    local src="$1"
    local dst="$2"

    if [[ "$IN_CONDATINER" -eq 1 ]]; then
        cp "$src" "$dst"
    else
        ln "$src" "$dst" || cp "$src" "$dst"
    fi
}

#endregion

install
