#!/usr/bin/bash
#WHATIS:GRCh38 RepeatMasker GTF
#URL:https://genome.ucsc.edu/cgi-bin/hgTables
#ENV:RMSK_GTF=$app_root/hg38_rmsk.gtf
#ENVNOTE:RepeatMasker GTF for GRCh38

#########################################################
# - https://genome.ucsc.edu/cgi-bin/hgTables?clade=mammal&org=Human&db=hg38&hgta_group=allTracks&hgta_track=rmsk&hgta_table=rmsk&hgta_regionType=genome&position=&hgta_outputType=gff&hgta_outFileName=hg38_rmsk.gtf&hgta_doTopSubmit=get+output
# Currently UCSC table browser requires a verification step (captcha) to download RMSK GTF for hg38
# So the file cannot be downloaded programmatically at this time.
#########################################################

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    cd "$target_dir"
    url="https://github.com/Justype/modules/releases/download/rmsk/hg38_rmsk.gtf.gz"
    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    wget -nv -O "hg38_rmsk.gtf.gz" "$url"

    print_stderr "Extracting ${YELLOW}${app_name_version}${NC}"
    pigz_or_gunzip "hg38_rmsk.gtf.gz"
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK
# - app_name:         name     of the app (set by condatainer)
# - version:          version  of the app (set by condatainer)
# - app_name_version: name/version        (set by condatainer)

# - target_dir:       opt/assembly/data_type/version (set by condatainer)
# - tmp_dir:          tmp directory (set by condatainer)

# region common_functions
set -e # exit on error
RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color
ncpu=${SLURM_CPUS_PER_TASK:-4} # number of cores to use when building from source

install() {
    print_stderr "Installing the target module: ${YELLOW}${app_name_version}${NC}"
    print_stderr "🎯 Target directory: $target_dir"
    # if target directory exists, exit 1
    if [ -d "$target_dir" ]; then
        print_stderr "${RED}ERROR${NC}: Target app dir exists!"
        print_stderr "Exit Installing"
        exit 1
    fi

    if [[ -z "$tmp_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: tmp_dir is not set!"
        print_stderr "Exit Installing"
        exit 1
    fi

    if [[ -z "$target_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: target_dir is not set!"
        print_stderr "Exit Installing"
        exit 1
    fi

    mkdir -p "$target_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    install_app
    print_stderr "✅ Installation completed. ${YELLOW}${app_name_version}${NC} is ready to use."
}

print_stderr() {
    printf "[`date +"%Y-%m-%d %T"`] $1\n" 1>&2
}

pigz_or_gunzip() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $ncpu "$1"
    else
        gunzip "$1"
    fi
}

pigz_or_gunzip_pipe() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $ncpu -c "$1"
    else
        gunzip -c "$1"
    fi
}

tar_xf_pigz() {
    if command -v pigz &> /dev/null; then
        tar --no-same-owner --use-compress-program="pigz -d -p $ncpu" -xf "$@"
    else
        tar --no-same-owner -xzf "$@"
    fi
}
#endregion

install

