#!/usr/bin/bash
#DEP:grch38/genome/gencode
#DEP:grch38/gtf-gencode/47
#DEP:grch38/vcf/hprc-v1.1-decomposed-gencode
#DEP:vg/1.61.0
#WHATIS:VG graph genome with GRCh38 and GENCODE47
#URL:https://github.com/vgteam/vg
#ENV:VG_XG=$app_root/hprc-v1.1-mc-grch38-gencode47.spliced.xg
#ENVNOTE:xg spliced genome index: vg mpmap, rpvg
#ENV:VG_DIST=$app_root/hprc-v1.1-mc-grch38-gencode47.spliced.dist
#ENVNOTE:dist index: vg mpmap
#ENV:VG_GCSA=$app_root/hprc-v1.1-mc-grch38-gencode47.spliced.gcsa
#ENVNOTE:gcsa2 index: vg mpmap
#ENV:VG_GCSA_LCP=$app_root/hprc-v1.1-mc-grch38-gencode47.spliced.gcsa.lcp
#ENVNOTE:gcsa2 lcp index: vg mpmap
#ENV:VG_GBWT=$app_root/hprc-v1.1-mc-grch38-gencode47.haplotx.gbwt
#ENVNOTE:gbwt haplotype paths: vg rpvg
#ENV:VG_GBWT_RI=$app_root/hprc-v1.1-mc-grch38-gencode47.haplotx.gbwt.ri
#ENVNOTE:gbwt index
#ENV:VG_TXORIGIN_TSV=$app_root/hprc-v1.1-mc-grch38-gencode47.txorigin.tsv
#ENVNOTE:transcript origin TSV: vg rpvg

#########################################################
# VG graph genome with GRCh38 and GENCODE47
# Using HPRC v1.1 variants (decomposed) to build the graph
# - VG is a graph genome toolkit
# - The RNA-seq results can be parsed by rpvg after mapping with VG
#########################################################

install_app() {
    # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
    mkdir -p vg-tmp
    
    print_stderr "Building VG graph index for ${YELLOW}${app_name_version}${NC}"
    vg autoindex --workflow mpmap --workflow rpvg \
        --prefix hprc-v1.1-mc-grch38-gencode47 \
        --ref-fasta $GENOME_FASTA \
        --tx-gff $ANNOTATION_GTF \
        --vcf $HPRC_GENCODE_VCF_GZ \
        --threads $ncpu \
        --target-mem 400G \
        --tmp-dir vg-tmp \
        --gcsa-size-limit 4398046511104 \
        --verbosity 2
    # 32 threads are recommended
    # You should allocate at least 400GB memory for building the graph
    # 4TB for gcsa-size-limit (increase temporary limit when building GCSA)

    print_stderr "Moving VG graph index files to target directory"
    mv hprc-v1.1-mc-grch38-gencode47.* "$target_dir/"
}

# Available variables:
# - ncpu: number of cores to use (default: 4) will be overwritten by SLURM_CPUS_PER_TASK
# - app_name:         name     of the app (set by condatainer)
# - version:          version  of the app (set by condatainer)
# - app_name_version: name/version        (set by condatainer)

# - target_dir:       opt/assembly/data_type/version (set by condatainer)
# - tmp_dir:          tmp directory (set by condatainer)

set -e # exit on error
RED='\033[0;91m'    # Red      WARNING or ERROR
BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
YELLOW='\033[0;93m' # Yellow   App Name and/or Version
NC='\033[0m'        # No Color
ncpu=${SLURM_CPUS_PER_TASK:-4} # number of cores to use when building from source

install() {
    print_stderr "Installing the target module: ${YELLOW}${app_name_version}${NC}"
    print_stderr "🎯 Target directory: $target_dir"
    # if target directory exists, exit 1
    if [ -d "$target_dir" ]; then
        print_stderr "${RED}ERROR${NC}: Target app dir exists!"
        print_stderr "Exit Installing"
        exit 1
    fi

    if [[ -z "$tmp_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: tmp_dir is not set!"
        print_stderr "Exit Installing"
        exit 1
    fi

    if [[ -z "$target_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: target_dir is not set!"
        print_stderr "Exit Installing"
        exit 1
    fi

    mkdir -p "$target_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    install_app
    print_stderr "✅ Installation completed. ${YELLOW}${app_name_version}${NC} is ready to use."
}

print_stderr() {
    printf "[`date +"%Y-%m-%d %T"`] $1\n" 1>&2
}

pigz_or_gunzip() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $ncpu "$1"
    else
        gunzip "$1"
    fi
}

pigz_or_gunzip_pipe() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $ncpu -c "$1"
    else
        gunzip -c "$1"
    fi
}

tar_xf_pigz() {
    if command -v pigz &> /dev/null; then
        tar --no-same-owner --use-compress-program="pigz -d -p $ncpu" -xf "$@"
    else
        tar --no-same-owner -xzf "$@"
    fi
}
#endregion

install
